/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-dim": "#e0f2fe",
        "surface-container-high": "#bae6fd",
        "tertiary-fixed-dim": "#ffb3b4",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#574500",
        "surface-container-highest": "#7dd3fc",
        "error": "#ef4444",
        "tertiary-fixed": "#ffdad9",
        "surface-tint": "#0284c7",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#713437",
        "inverse-primary": "#38bdf8",
        "outline-variant": "#cbd5e1",
        "tertiary-container": "#713437",
        "background": "#f0f9ff",
        "on-primary-fixed": "#075985",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#bae6fd",
        "surface-bright": "#ffffff",
        "primary-fixed": "#e0f2fe",
        "primary-container": "#0ea5e9",
        "secondary": "#735c00",
        "on-tertiary-fixed": "#3a090f",
        "outline": "#64748b",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#745c00",
        "surface-container": "#f0f9ff",
        "error-container": "#fee2e2",
        "on-background": "#0c4a6e",
        "surface-variant": "#f0f9ff",
        "on-primary-fixed-variant": "#0369a1",
        "surface": "#ffffff",
        "on-secondary-fixed": "#241a00",
        "secondary-container": "#fed65b",
        "surface-container-low": "#f8fafc",
        "secondary-fixed-dim": "#e9c349",
        "inverse-surface": "#0f172a",
        "secondary-fixed": "#ffe088",
        "inverse-on-surface": "#f0f9ff",
        "tertiary": "#551e22",
        "on-error-container": "#991b1b",
        "on-surface-variant": "#64748b",
        "on-tertiary-container": "#f29fa1",
        "primary": "#0284c7",
        "on-surface": "#0f172a",
        "on-primary-container": "#ffffff",
        "on-error": "#ffffff",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
      spacing: {
        "xl": "80px",
        "md": "24px",
        "base": "8px",
        "sm": "12px",
        "margin-mobile": "20px",
        "lg": "48px",
        "xs": "4px",
        "margin-desktop": "64px",
        "gutter": "24px",
      },
      fontFamily: {
        "sans": ["Inter", "sans-serif"],
        "serif": ["Inter", "sans-serif"],
        "button": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "title-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "button": ["14px", { "lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "0em", "fontWeight": "600" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.08em", "fontWeight": "600" }],
        "body-sm": ["14px", { "lineHeight": "20px", "letterSpacing": "0em", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "24px", "letterSpacing": "0em", "fontWeight": "400" }],
        "display-lg-mobile": ["32px", { "lineHeight": "40px", "letterSpacing": "0em", "fontWeight": "600" }],
        "display-lg": ["44px", { "lineHeight": "52px", "letterSpacing": "0em", "fontWeight": "700" }],
        "title-sm": ["18px", { "lineHeight": "24px", "letterSpacing": "0em", "fontWeight": "600" }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
