/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-dim": "#d7dadf",
        "surface-container-high": "#e5e8ee",
        "tertiary-fixed-dim": "#ffb3b4",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#574500",
        "surface-container-highest": "#e0e3e8",
        "error": "#ba1a1a",
        "tertiary-fixed": "#ffdad9",
        "surface-tint": "#2d6a48",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#713437",
        "inverse-primary": "#95d4ac",
        "outline-variant": "#c0c9c0",
        "tertiary-container": "#713437",
        "background": "#f7f9ff",
        "on-primary-fixed": "#002111",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#95d4ac",
        "surface-bright": "#f7f9ff",
        "primary-fixed": "#b0f1c7",
        "primary-container": "#0f5132",
        "secondary": "#735c00",
        "on-tertiary-fixed": "#3a090f",
        "outline": "#707971",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#745c00",
        "surface-container": "#ebeef3",
        "error-container": "#ffdad6",
        "on-background": "#181c20",
        "surface-variant": "#e0e3e8",
        "on-primary-fixed-variant": "#0f5132",
        "surface": "#f7f9ff",
        "on-secondary-fixed": "#241a00",
        "secondary-container": "#fed65b",
        "surface-container-low": "#f1f4f9",
        "secondary-fixed-dim": "#e9c349",
        "inverse-surface": "#2d3135",
        "secondary-fixed": "#ffe088",
        "inverse-on-surface": "#eef1f6",
        "tertiary": "#551e22",
        "on-error-container": "#93000a",
        "on-surface-variant": "#404942",
        "on-tertiary-container": "#f29fa1",
        "primary": "#003820",
        "on-surface": "#181c20",
        "on-primary-container": "#84c39b",
        "on-error": "#ffffff",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
      spacing: {
        "xl": "80px",
        "md": "24px",
        "base": "8px",
        "sm": "12px",
        "margin-mobile": "20px",
        "lg": "48px",
        "xs": "4px",
        "margin-desktop": "64px",
        "gutter": "24px",
      },
      fontFamily: {
        "sans": ["Inter", "sans-serif"],
        "serif": ["Inter", "sans-serif"],
        "button": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "title-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "button": ["14px", { "lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "0em", "fontWeight": "600" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.08em", "fontWeight": "600" }],
        "body-sm": ["14px", { "lineHeight": "20px", "letterSpacing": "0em", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "24px", "letterSpacing": "0em", "fontWeight": "400" }],
        "display-lg-mobile": ["32px", { "lineHeight": "40px", "letterSpacing": "0em", "fontWeight": "600" }],
        "display-lg": ["44px", { "lineHeight": "52px", "letterSpacing": "0em", "fontWeight": "700" }],
        "title-sm": ["18px", { "lineHeight": "24px", "letterSpacing": "0em", "fontWeight": "600" }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
