name: Deploy Frontend to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-push-fe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image FE
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/clothing-shop-fe:latest
          build-args: |
            VITE_API_BASE_URL=https://sapo.id.vn

  deploy-fe-to-vps:
    needs: build-and-push-fe
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands to deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/clothing-shop-pos
            docker compose pull clothing-shop-fe
            docker compose up -d clothing-shop-fe